![LOGO-INTI SMART_LOGO HORIZONTAL-POSITIVO.png]()

# Fundamentos de Python

### Guía Completa para Principiantes  2025

# **Índice**

1. Introducción a Python
2. Tipos de datos y variables
3. Operadores
4. Estructuras de control
5. Estructuras de datos
6. Funciones y control de flujo
7. Clases y objetos

# 1. Introducción a Python

¿Qué es?
- Es un lenguaje de programación fácil de aprender y extremadamente versátil. Creado por Guido van Rossum en 1991 y al día de hoy se ha convertido en uno de los lenguajes más populares del mundo.

¿Por qué aprender Python?
- Fácil de leer: Su sintaxis es clara y similar al lenguaje humano.
- Versátil: Sirve para desarrollo web, ciencia de datos, inteligencia artificial, automatización y más.
- Gran comunidad: Millones de programadores en todo el mundo que pueden interactuar.
- Diversidad de bibliotecas: Miles de herramientas ya creadas que puedes usar.

# 2. Tipos de Datos y Variables

¿Qué es una variable?
- Es un espacio de almacenamiento al que se le asigna un nombre simbólico. Este nombre nos permite guardar y recuperar diferentes tipos de datos (números, texto, etc.) para utilizarlos o modificarlos a lo largo de la ejecución del programa.

### 2.1. Números Enteros ("int")

In [ ]:
edad = 25
temperatura = -5
poblacion = 1000000

print(edad)  # 25
print(type(edad))  # <class 'int'>

25
<class 'int'>

### Números Decimales ("float")

In [ ]:
altura = 1.75
precio = 19.99
pi = 3.14159

print(altura)  # 1.75
print(type(altura))  # <class 'float'>

1.75
<class 'float'>

### Conversiones entre tipos numéricos

In [ ]:
# De float a int (se pierde la parte decimal)
numero_decimal = 7.8
numero_entero = int(numero_decimal)
print(numero_entero)  # 7

7

In [ ]:
# De int a float
entero = 10
decimal = float(entero)
print(decimal)  # 10.0

10.0

In [ ]:
# De string a número
texto = "42"
numero = int(texto)
print(numero + 8)  # 50

50

### 2.2. Booleanos (True/False)

Los booleanos solo tienen dos valores posibles: True (verdadero) o False (falso).

In [ ]:
esta_lloviendo = True
tengo_hambre = False

print(esta_lloviendo)  # True
print(type(esta_lloviendo))  # <class 'bool'>

True
<class 'bool'>

### 2.3. Cadenas de Texto (Strings)

In [ ]:
nombre = "María"
apellido = 'González'
mensaje = "¡Hola, mundo!"

print(nombre)  # María
print(type(nombre))  # <class 'str'>

María
<class 'str'>

### 2.4 Operaciones con strings

In [ ]:
nombre = "Ana"
apellido = "Torres"
nombre_completo = nombre + " " + apellido
print(nombre_completo)  # Ana Torres

Ana Torres

In [ ]:
# Repetición
risa = "ja" * 5
print(risa)  # jajajajaja

jajajajaja

In [ ]:
# Conversión a mayúsculas y minúsculas
texto = "Hola Mundo"
print(texto.upper())  # HOLA MUNDO
print(texto.lower())  # hola mundo
print(texto.title())  # Hola Mundo

HOLA MUNDO
hola mundo
Hola Mundo

### 2.5 Entrada de datos del usuario

In [ ]:
# Pedir información al usuario
nombre = input("¿Cómo te llamas? ")
print("Hola, " + nombre)

¿Cómo te llamas? IntiSmart
Hola, IntiSmart

In [ ]:
# Convertir entrada a número
edad = int(input("¿Cuántos años tienes? "))
print("El próximo año tendrás", edad + 1, "años")

¿Cuántos años tienes? 20
El próximo año tendrás 21 años

### 2.6 Variables múltiples

In [ ]:
# Asignar varios valores a la vez
x, y, z = 10, 20, 30
print(x)  # 10
print(y)  # 20
print(z)  # 30

10
20
30

In [ ]:
# Asignar el mismo valor a varias variables
a = b = c = 100
print(a, b, c)  # 100 100 100

100 100 100

# 3. Operadores

### 3.1. Operadores Aritméticos

In [ ]:
# Suma
resultado = 10 + 5
print(resultado)  # 15

15

In [ ]:
# Resta
resultado = 20 - 8
print(resultado)  # 12

12

In [ ]:
# Multiplicación
resultado = 6 * 7
print(resultado)  # 42

42

In [ ]:
# División (siempre da un float)
resultado = 15 / 4
print(resultado)  # 3.75

3.75

In [ ]:
# División entera (solo la parte entera)
resultado = 15 // 4
print(resultado)  # 3

3

In [ ]:
# Módulo (resto de la división)
resultado = 15 % 4
print(resultado)  # 3

3

In [ ]:
# Potencia
resultado = 2 ** 3
print(resultado)  # 8

8

In [ ]:
# Raíz cuadrada (usando potencia)
resultado = 16 ** 0.5
print(resultado)  # 4.0

4.0

In [ ]:
## Orden de operaciones
# Python sigue las reglas matemáticas normales:
resultado = 2 + 3 * 4
print(resultado)  # 14 (primero 3*4=12, luego 2+12=14)

14

In [ ]:
# Con paréntesis
resultado = (2 + 3) * 4
print(resultado)  # 20 (primero 2+3=5, luego 5*4=20)

20

In [ ]:
# Calcular el área de un círculo
radio = 5
pi = 3.14159
area = pi * radio ** 2
print("El área es:", area)  # 78.53975

El área es: 78.53975

In [ ]:
# Convertir temperatura de Celsius a Fahrenheit
celsius = 25
fahrenheit = (celsius * 9/5) + 32
print(f"{celsius}°C = {fahrenheit}°F")  # 25°C = 77.0°F

25°C = 77.0°F

In [ ]:
# Calcular si un número es par o impar
numero = 17
if numero % 2 == 0:
    print("Es par")
else:
    print("Es impar")  # Es impar

Es impar

### 3.2. Operadores de Comparación

Estos operadores comparan dos valores y devuelven True o False.

In [ ]:
# Igual a
print(5 == 5)   # True
print(5 == 3)   # False

True
False

In [ ]:
# Diferente de
print(5 != 3)   # True
print(5 != 5)   # False

True
False

In [ ]:
# Mayor que
print(8 > 5)    # True
print(3 > 10)   # False

True
False

In [ ]:
# Menor que
print(3 < 7)    # True
print(9 < 2)    # False

True
False

In [ ]:
# Mayor o igual que
print(5 >= 5)   # True
print(5 >= 3)   # True
print(2 >= 8)   # False

True
True
False

In [ ]:
# Menor o igual que
print(3 <= 5)   # True
print(7 <= 7)   # True
print(9 <= 4)   # False

True
True
False

### 3.3.Comparación de strings (orden lexicográfico)

Python compara strings letra por letra, siguiendo el orden del diccionario.

In [ ]:
print("apple" < "banana")   # True (a viene antes que b)
print("casa" < "perro")     # True
print("gato" < "gatos")     # True (más corto viene primero)
print("Python" < "python")  # True (mayúsculas van antes)

True
True
True
True

In [ ]:
# Cuidado con mayúsculas y minúsculas
print("Zebra" < "apple")    # True (Z mayúscula < a minúscula)

True

### 3.4. Operadores Lógicos

Se usan para combinar condiciones.

In [ ]:
# AND (y) - ambas condiciones deben ser True
edad = 25
tiene_licencia = True
print(edad >= 18 and tiene_licencia)  # True

True

In [ ]:
edad = 16
print(edad >= 18 and tiene_licencia)  # False

False

In [ ]:
# OR (o) - al menos una condición debe ser True
es_fin_de_semana = True
es_feriado = False
print(es_fin_de_semana or es_feriado)  # True

True

In [ ]:
# NOT (no) - invierte el valor
esta_lloviendo = False
print(not esta_lloviendo)  # True

True

Tabla de verdad

In [ ]:
# AND
print(True and True)    # True
print(True and False)   # False
print(False and True)   # False
print(False and False)  # False

True
False
False
False

In [ ]:
# OR
print(True or True)     # True
print(True or False)    # True
print(False or True)    # True
print(False or False)   # False

True
True
True
False

In [ ]:
# NOT
print(not True)   # False
print(not False)  # True

False
True

In [ ]:
# Verificar si un número está en un rango
numero = 15
en_rango = numero >= 10 and numero <= 20
print(en_rango)  # True

True

In [ ]:
# Verificar acceso a un sistema
usuario = "admin"
password = "1234"
acceso_permitido = usuario == "admin" and password == "1234"
print(acceso_permitido)  # True

True

### 3.5. Operadores de Asignación

In [ ]:
# Asignación simple
x = 10
print(x)  # 10

10

In [ ]:
# Suma y asignación
x += 5  # equivale a: x = x + 5
print(x)  # 15

15

In [ ]:
# Resta y asignación
x -= 3  # equivale a: x = x - 3
print(x)  # 12

12

In [ ]:
# Multiplicación y asignación
x *= 2  # equivale a: x = x * 2
print(x)  # 24

24

In [ ]:
# División y asignación
x /= 4  # equivale a: x = x / 4
print(x)  # 6.0

6.0

In [ ]:
# División entera y asignación
x //= 2  # equivale a: x = x // 2
print(x)  # 3.0

3.0

In [ ]:
# Módulo y asignación
x %= 2  # equivale a: x = x % 2
print(x)  # 1.0

1.0

In [ ]:
# Potencia y asignación
x = 2
x **= 3  # equivale a: x = x ** 3
print(x)  # 8

8

### 3.6. Operador ternario (if-else en una línea)

In [ ]:
edad = 17
mensaje = "Mayor de edad" if edad >= 18 else "Menor de edad"
print(mensaje)  # Menor de edad

Menor de edad

In [ ]:
# Otro ejemplo
temperatura = 28
clima = "Calor" if temperatura > 25 else "Frío"
print(clima)  # Calor

Calor

### 3.7. Operadores de Identidad (is  - verifica si son iguales)

Compara si dos variables apuntan al mismo objeto en memoria.

In [ ]:
x = [1, 2, 3]
y = x
z = [1, 2, 3]

print(x is y)  # True (y apunta al mismo objeto que x)
print(x is z)  # False (z es un objeto diferente)
# is not
print(x is not z)  # True

True
False
True

In [ ]:
# Comparación de valores vs identidad
print(x == z)  # True (tienen los "mismos valores")
print(x is z)  # False (son "objetos diferentes")

True
False

### 3.8. Operadores de Pertenencia (in)

Verifican si un valor está presente en una secuencia.

In [ ]:
frutas = ["manzana", "pera", "uva"]
print("pera" in frutas)  # True
print("sandía" in frutas)  # False
# Mientras que "not in" - verifica que no está presente
print("sandía" not in frutas)  # True

True
False
True

In [ ]:
# Con strings
texto = "Python es genial"
print("Python" in texto)  # True
print("Java" in texto)  # False

True
False

In [ ]:
# Con diccionarios (verifica los keys)
edades = {"Ana": 25, "Luis": 30}
print("Ana" in edades)  # True
print(25 in edades)  # False (25 es un valor, no un key)

True
False

# 4. Estructuras de Control
### 4.1. Condicionales

In [ ]:
edad = 20
# if -- si
if edad >= 18:
    print("Eres mayor de edad")
    print("Puedes votar")
# else -- sino
else:
  print("no puedes votar")

Eres mayor de edad
Puedes votar

In [ ]:
temperatura = 15
if temperatura > 20:
    print("Hace calor")
else:
    print("Hace frío")

Hace frío

In [ ]:
# Cuando if-elif-else  <--> si-sino si-sino
nota = 16
if nota >= 18:
    print("Excelente")
elif nota >= 14:
    print("Bueno")
elif nota >= 11:
    print("Regular")
else:
    print("Insuficiente")

Bueno

In [ ]:
## Condicionales anidados
edad = 25
tiene_licencia = True

if edad >= 18:
    if tiene_licencia:
        print("Puedes conducir")
    else:
        print("Necesitas sacar tu licencia")
else:
    print("Eres menor de edad")

Puedes conducir

In [ ]:
## Múltiples condiciones
usuario = "inti"
password = "1234"

if usuario == "inti" and password == "1234":
    print("Acceso concedido")
else:
    print("Acceso denegado")

Acceso concedido

### 4.2. Bucles (Loops)

Nos permiten repetir código múltiples veces.

In [ ]:
## for -- para
## El bucle for itera sobre una secuencia (lista, rango, string, etc.).
# -------------------Iterando sobre una lista-----------------------------------
frutas = ["manzana", "pera", "uva"]
for fruta in frutas:
    print(fruta)

manzana
pera
uva

In [ ]:
for i in range(5):  # "i" es mi variable
    print(i)

0
1
2
3
4

In [ ]:
# Rango con inicio y fin
for i in range(2, 8):
    print(i)

2
3
4
5
6
7

In [ ]:
# Rango con paso
for i in range(0, 10, 2):
    print(i)

# Iterar sobre un string
palabra = "Python"
for letra in palabra:
    print(letra)

0
2
4
6
8
P
y
t
h
o
n

In [ ]:
## while -- mientras
# El bucle while se repite mientras una condición sea verdadera.
contador = 0
while contador < 5:
    print(contador)
    contador += 1  #incremento

0
1
2
3
4

In [ ]:
# Adivina un número
numero_secreto = 7
intento = 0

while intento != numero_secreto:
    intento = int(input("Adivina el número (1-10): "))  ##  introducir en el comando
    if intento < numero_secreto:
        print("Muy bajo")
    elif intento > numero_secreto:
        print("Muy alto")

print("¡Correcto!")

Adivina el número (1-10): 8
Muy alto
Adivina el número (1-10): 7
¡Correcto!

# 5. Estructuras de Datos
### 5.1. Listas

Son colecciones ordenadas y modificables de elementos.

In [ ]:
numeros = [1, 2, 3, 4, 5]
frutas = ["manzana", "pera", "uva"]
mixta = [1, "dos", 3.0, True]
print(numeros)
print(mixta)

[1, 2, 3, 4, 5]
[1, 'dos', 3.0, True]

In [ ]:
frutas = ["manzana", "pera", "uva", "sandía"]
# Por índice (comienza en 0)
print(frutas[0])   # manzana
print(frutas[2])   # uva
# Índices negativos (desde el final)
print(frutas[-1])  # sandía (último)
print(frutas[-2])  # uva (penúltimo)

manzana
uva
sandía
uva

In [ ]:
# Slicing (porciones)
print(frutas[1:3])   # ['pera', 'uva']
print(frutas[:2])    # ['manzana', 'pera']
print(frutas[2:])    # ['uva', 'sandía']

['pera', 'uva']
['manzana', 'pera']
['uva', 'sandía']

In [ ]:
## Modificando diccionarios
# Agregar o modificar
persona={}
persona["telefono"] = "987654321"
persona["edad"] = 26
print(persona)

{'telefono': '987654321', 'edad': 26}

In [ ]:
# Eliminar y retornar
telefono = persona.pop("telefono")
print(telefono)
print(persona)

987654321
{'edad': 26}

In [ ]:
# Vaciar
persona.clear()
print(persona)  # {}

{}

**Métodos útiles**

In [ ]:
# clave - valor
estudiante = {
    "nombre": "Carlos",
    "edad": 20,
    "carrera": "Ingeniería"
}
print(estudiante)

# Obtener claves
print(estudiante.keys())  # dict_keys(['nombre', 'edad', 'carrera'])

# Obtener valores
print(estudiante.values())  # dict_values(['Carlos', 20, 'Ingeniería'])

# Obtener pares clave-valor
print(estudiante.items())
# dict_items([('nombre', 'Carlos'), ('edad', 20), ('carrera', 'Ingeniería')])

# Verificar existencia
print("nombre" in estudiante)  # True
print("telefono" in estudiante)  # False

{'nombre': 'Carlos', 'edad': 20, 'carrera': 'Ingeniería'}
dict_keys(['nombre', 'edad', 'carrera'])
dict_values(['Carlos', 20, 'Ingeniería'])
dict_items([('nombre', 'Carlos'), ('edad', 20), ('carrera', 'Ingeniería')])
True
False

In [ ]:
# Iterar sobre claves
for clave in estudiante:
    print(clave)

# Iterar sobre valores
for valor in estudiante.values():
    print(valor)

# Iterar sobre claves y valores
for clave, valor in estudiante.items():
    print(f"{clave}: {valor}")

nombre
edad
carrera
Carlos
20
Ingeniería
nombre: Carlos
edad: 20
carrera: Ingeniería

In [ ]:
## Diccionarios anidados
# Diccionario de diccionarios
escuela = {
    "estudiante1": {
        "nombre": "Ana",
        "edad": 20,
        "notas": [15, 18, 16]
    },
    "estudiante2": {
        "nombre": "Luis",
        "edad": 21,
        "notas": [14, 16, 15]
    }
}

print(escuela["estudiante1"]["nombre"])  # Ana
print(escuela["estudiante1"]["notas"][0])  # 15

Ana
15

**Matrices** **(Listas de listas)**

In [ ]:
# Crear una matriz
matriz = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [ ]:
# Acceder a elementos
print(matriz[0])     # [1, 2, 3] (primera fila)
print(matriz[1][2])  # 6 (fila 1, columna 2)

[1, 2, 3]
6

In [ ]:
# Recorrer una matriz
for fila in matriz:
    for elemento in fila:
        print(elemento, end=" ")
    print()  # Nueva línea

1 2 3
4 5 6
7 8 9

In [ ]:
# Crear matriz con bucles
filas = 3
columnas = 4
matriz = []

for i in range(filas):
    fila = []
    for j in range(columnas):
        fila.append(0)
    matriz.append(fila)

print(matriz)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

In [ ]:
# Forma más simple de crear matriz de ceros
matriz = [[0]*4 for i in range(3)]
print(matriz)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

# 6. Funciones y Control de Flujo
### 6.1. break (romper el bucle)

La palabra break termina el bucle inmediatamente.

In [ ]:
# Buscar un número específico
numeros = [1, 3, 5, 7, 9, 11]
buscar = 7

for num in numeros:
    if num == buscar:
        print(f"¡Encontrado! {num}")
        break
    print(num)

1
3
5
¡Encontrado! 7

In [ ]:
# Salir de un bucle while
contador = 0
while True:             # Bucle infinito
    print(contador)
    contador += 1
    if contador >= 5:
        break

0
1
2
3
4

### 6.2. continue (saltar a la siguiente iteración)

Es decir, salta el resto del código y va a la siguiente iteración.

In [ ]:
# Imprimir solo números impares
for i in range(10):
    if i % 2 == 0:  # Si es par
        continue    # Salta el print
    print(i)

1
3
5
7
9

In [ ]:
# Saltar valores específicos
frutas = ["manzana", "banana", "pera", "uva"]
for fruta in frutas:
    if fruta == "banana":
        continue
    print(fruta)

manzana
pera
uva

### 6.3. range (rango)

La función range() genera una secuencia de números.

In [ ]:
# range(fin) --> desde 0 hasta fin-1
for i in range(5):
    print(i)

# range(inicio, fin)
for i in range(3, 8):
    print(i)
# Salida: 3, 4, 5, 6, 7

# range(inicio, fin, paso)
for i in range(0, 10, 2):
    print(i)
# Salida: 0, 2, 4, 6, 8

# Rango decreciente
for i in range(10, 0, -1):
    print(i)

# Convertir range a lista
numeros = list(range(5))
print(numeros)  # [0, 1, 2, 3, 4]

0
1
2
3
4
3
4
5
6
7
0
2
4
6
8
10
9
8
7
6
5
4
3
2
1

### 6.4. pass (marcador de posición)

 Pass es un marcador que no hace nada. Se usa cuando se requiere código pero aún no quieres escribirlo.

In [ ]:
# Función vacía (por ahora)
def mi_funcion():
    pass  # La implementaré después

# Clase vacía
class MiClase:
    pass

# Condicional vacío
x = 10
if x > 5:
    pass  # Todavía no sé qué hacer aquí
else:
    print("x es pequeño")

### 6.5. Definición de Funciones (def)

Las funciones son bloques de código reutilizables.

In [ ]:
# Función simple
def saludar():
    print("¡Hola!")
saludar()  # ¡Hola!

# Con un parámetro
def saludar_persona(nombre):
    print(f"¡Hola, {nombre}!")

saludar_persona("Ana")  # ¡Hola, Ana!
saludar_persona("Luis")  # ¡Hola, Luis!

# Con múltiples parámetros
def sumar(a, b):
    resultado = a + b
    print(f"{a} + {b} = {resultado}")

sumar(5, 3)  # 5 + 3 = 8

¡Hola!
¡Hola, Ana!
¡Hola, Luis!
5 + 3 = 8

In [ ]:
# Retornar un valor
def multiplicar(a, b):
    return a * b
resultado = multiplicar(4, 5)
print(resultado)  # 20

# Usar el resultado en otra operación
total = multiplicar(3, 7) + 10
print(total)  # 31

# Retornar múltiples valores
def operaciones(a, b):
    suma = a + b
    resta = a - b
    producto = a * b
    return suma, resta, producto

s, r, p = operaciones(10, 5)
print(f"Suma: {s}, Resta: {r}, Producto: {p}") # Suma: 15, Resta: 5, Producto: 50

# Valor por defecto
def saludar(nombre="amigo"):
    print(f"¡Hola, {nombre}!")

saludar()        # ¡Hola, amigo!
saludar("Ana")   # ¡Hola, Ana!

# Múltiples parámetros con valores por defecto
def crear_perfil(nombre, edad=18, ciudad="Lima"):
    print(f"{nombre}, {edad} años, vive en {ciudad}")

crear_perfil("Ana")                    # Ana, 18 años, vive en Lima
crear_perfil("Luis", 25)               # Luis, 25 años, vive en Lima
crear_perfil("María", 30, "Arequipa")  # María, 30 años, vive en Arequipa

20
31
Suma: 15, Resta: 5, Producto: 50
¡Hola, amigo!
¡Hola, Ana!
Ana, 18 años, vive en Lima
Luis, 25 años, vive en Lima
María, 30 años, vive en Arequipa

In [ ]:
# Calculando el área de un círculo. -- Parámetro: radio (float): El radio del círculo
from math import pi
radio=float(input("Inserta el valor del radio (m):"))
def calcular_area_circulo(radio):
    return (pi) * (radio ** 2) #Retorna:float: El área del círculo
print(f"El area del circulo es:{calcular_area_circulo(radio)} m2")

Inserta el valor del radio (m):5
El area del circulo es:78.53981633974483 m2

In [ ]:
# Función para verificar si un número es par
def es_par(numero):
    return numero % 2 == 0
print(es_par(4))   # True
print(es_par(7))   # False
#---------------------------------------------------------
# Función para calcular el promedio de una lista
def calcular_promedio(lista):
    if len(lista) == 0:
        return 0
    return sum(lista) / len(lista)
notas = [15, 18, 16, 14, 17]
promedio = calcular_promedio(notas)
print(f"Promedio: {promedio}")  # Promedio: 16.0
#----------------------------------------------------------
# Función para encontrar el máximo de tres números
def maximo_tres(a, b, c):
    if a >= b and a >= c:
        return a
    elif b >= a and b >= c:
        return b
    else:
        return c
print(maximo_tres(10, 25, 15))  # 25

True
False
Promedio: 16.0
25

In [ ]:
# Función para verificar si un año es bisiesto
def es_bisiesto(año):
    if año % 4 == 0:
        if año % 100 == 0:
            if año % 400 == 0:
                return True
            else:
                return False
        else:
            return True
    else:
        return False

print(es_bisiesto(2024))  # True
print(es_bisiesto(2023))  # False

True
False

### 6.6. Funciones Lambda

Las funciones lambda son funciones anónimas de una sola línea.

In [ ]:
# Función normal
def cuadrado(x):
    return x ** 2
print(cuadrado(5))  # 25

# Equivalente con lambda
cuadrado = lambda x: x ** 2
print(cuadrado(5))  # 25

# Lambda con múltiples parámetros
suma = lambda a, b: a + b
print(suma(3, 7))  # 10

multiplicar = lambda a, b, c: a * b * c
print(multiplicar(2, 3, 4))  # 24

25
25
10
24

**Lambda** **con funciones integradas**

In [ ]:
# Ordenar lista de tuplas por segundo elemento
estudiantes = [("Ana", 18), ("Luis", 15), ("María", 20)]
estudiantes.sort(key=lambda x: x[1])
print(estudiantes)
# [('Luis', 15), ('Ana', 18), ('María', 20)]

[('Luis', 15), ('Ana', 18), ('María', 20)]

In [ ]:
# Filtrar números pares
numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
pares = list(filter(lambda x: x % 2 == 0, numeros))
print(pares)  # [2, 4, 6, 8, 10]

[2, 4, 6, 8, 10]

In [ ]:
# Duplicar cada número
duplicados = list(map(lambda x: x * 2, numeros))
print(duplicados)  # [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

**Composición** **de funciones**

In [ ]:
# Crear funciones que retornan funciones
def crear_multiplicador(n):
    return lambda x: x * n

duplicar = crear_multiplicador(2)
triplicar = crear_multiplicador(3)

print(duplicar(5))   # 10
print(triplicar(5))  # 15

10
15

# 7. Clases y Objetos
La programación orientada a objetos (POO) permite organizar el código en objetos que tienen propiedades y comportamientos.

### 7.1. Definición de Clases

Una clase es como un molde o plantilla para crear objetos.

In [ ]:
# Clase simple
class Persona:
    pass  # Clase vacía por ahora

In [ ]:
# Crear un objeto
persona1 = Persona()
print(persona1)  # <__main__.Persona object at 0x...>

<__main__.Persona object at 0x7877889bd9d0>

Clase con atributos

In [ ]:
class Coche:
    # Atributo de clase (compartido por todos los objetos)
    ruedas = 4

# Crear objetos
coche1 = Coche()
coche2 = Coche()

print(coche1.ruedas)  # 4
print(coche2.ruedas)  # 4

4
4

### 7.2. El método init (Constructor)

El método (__init__) se ejecuta automáticamente al crear un objeto.

In [ ]:
class Persona:
    def __init__(self, nombre, edad):
        self.nombre = nombre  # Atributo de instancia
        self.edad = edad

In [ ]:
# Crear objetos
persona1 = Persona("Ana", 25)
persona2 = Persona("Luis", 30)

In [ ]:
print(persona1.nombre)  # Ana
print(persona1.edad)    # 25
print(persona2.nombre)  # Luis

Ana
25
Luis

**¿Qué es self?**

Representa la instancia actual del objeto. Es como decir "este objeto".

In [ ]:
class Rectangulo:
    def __init__(self, ancho, alto):
        self.ancho = ancho   # self.ancho pertenece a este objeto
        self.alto = alto

rect1 = Rectangulo(5, 10)
rect2 = Rectangulo(3, 7)

print(rect1.ancho)  # 5
print(rect2.ancho)  # 3

5
3

### 7.3. Métodos de Objetos

Los métodos son funciones dentro de una clase.

In [ ]:
class Persona:
    def __init__(self, nombre, edad):
        self.nombre = nombre
        self.edad = edad

    def saludar(self):
        print(f"Hola, soy {self.nombre}")

    def cumplir_años(self):
        self.edad += 1
        print(f"¡Feliz cumpleaños! Ahora tengo {self.edad} años")

In [ ]:
# Usar la clase
persona = Persona("Ana", 25)
persona.saludar()        # Hola, soy Ana
persona.cumplir_años()   # ¡Feliz cumpleaños! Ahora tengo 26 años

Hola, soy Ana
¡Feliz cumpleaños! Ahora tengo 26 años

**Métodos con parámetros**

In [ ]:
class CuentaBancaria:
    def __init__(self, titular, saldo=0):
        self.titular = titular
        self.saldo = saldo

    def depositar(self, cantidad):
        self.saldo += cantidad
        print(f"Depósito: ${cantidad}. Nuevo saldo: ${self.saldo}")

    def retirar(self, cantidad):
        if cantidad > self.saldo:
            print("Saldo insuficiente")
        else:
            self.saldo -= cantidad
            print(f"Retiro: ${cantidad}. Nuevo saldo: ${self.saldo}")

    def mostrar_saldo(self):
        print(f"Saldo de {self.titular}: ${self.saldo}")

In [ ]:
# Usar la clase
cuenta = CuentaBancaria("Ana", 1000)
cuenta.mostrar_saldo()   # Saldo de Ana: $1000
cuenta.depositar(500)    # Depósito: $500. Nuevo saldo: $1500
cuenta.retirar(300)      # Retiro: $300. Nuevo saldo: $1200

Saldo de Ana: $1000
Depósito: $500. Nuevo saldo: $1500
Retiro: $300. Nuevo saldo: $1200

**El método str (representación en string)**

In [ ]:
class Persona:
    def __init__(self, nombre, edad):
        self.nombre = nombre
        self.edad = edad

    def __str__(self):
        return f"{self.nombre} ({self.edad} años)"

persona = Persona("Ana", 25)
print(persona)  # Ana (25 años)

Ana (25 años)

## Ejemplos Completos

### Ejemplo 1: Sistema de Estudiantes

In [ ]:
class Estudiante:
    def __init__(self, nombre, codigo):
        self.nombre = nombre
        self.codigo = codigo
        self.notas = []

    def agregar_nota(self, nota):
        if 0 <= nota <= 20:
            self.notas.append(nota)
            print(f"Nota {nota} agregada")
        else:
            print("Nota inválida (debe estar entre 0 y 20)")

    def calcular_promedio(self):
        if len(self.notas) == 0:
            return 0
        return sum(self.notas) / len(self.notas)

    def mostrar_info(self):
        promedio = self.calcular_promedio()
        print(f"\n--- Información del Estudiante ---")
        print(f"Nombre: {self.nombre}")
        print(f"Código: {self.codigo}")
        print(f"Notas: {self.notas}")
        print(f"Promedio: {promedio:.2f}")

        if promedio >= 10.5:
            print("Estado: APROBADO ✓")
        else:
            print("Estado: DESAPROBADO ✗")

In [ ]:
# Usar la clase
estudiante = Estudiante("Carlos Pérez", "20230001")
estudiante.agregar_nota(15)
estudiante.agregar_nota(18)
estudiante.agregar_nota(16)
estudiante.mostrar_info()

Nota 15 agregada
Nota 18 agregada
Nota 16 agregada

--- Información del Estudiante ---
Nombre: Carlos Pérez
Código: 20230001
Notas: [15, 18, 16]
Promedio: 16.33
Estado: APROBADO ✓

### Ejemplo 2: Calculadora de Formas Geométricas

In [ ]:
class Circulo:
    def __init__(self, radio):
        self.radio = radio
        self.pi = 3.14159

    def calcular_area(self):
        return self.pi * self.radio ** 2

    def calcular_perimetro(self):
        return 2 * self.pi * self.radio

    def __str__(self):
        return f"Círculo de radio {self.radio}"

class Rectangulo:
    def __init__(self, ancho, alto):
        self.ancho = ancho
        self.alto = alto

    def calcular_area(self):
        return self.ancho * self.alto

    def calcular_perimetro(self):
        return 2 * (self.ancho + self.alto)

    def __str__(self):
        return f"Rectángulo de {self.ancho}x{self.alto}"

In [ ]:
# Usar las clases
circulo = Circulo(5)
print(circulo)
print(f"Área: {circulo.calcular_area():.2f}")
print(f"Perímetro: {circulo.calcular_perimetro():.2f}")

print()

rectangulo = Rectangulo(4, 6)
print(rectangulo)
print(f"Área: {rectangulo.calcular_area()}")
print(f"Perímetro: {rectangulo.calcular_perimetro()}")

Círculo de radio 5
Área: 78.54
Perímetro: 31.42

Rectángulo de 4x6
Área: 24
Perímetro: 20

### Ejemplo 3: Lista de Tareas

In [ ]:
class Tarea:
    def __init__(self, descripcion):
        self.descripcion = descripcion
        self.completada = False

    def marcar_completada(self):
        self.completada = True

    def __str__(self):
        estado = "✓" if self.completada else "○"
        return f"[{estado}] {self.descripcion}"

class ListaTareas:
    def __init__(self):
        self.tareas = []

    def agregar_tarea(self, descripcion):
        tarea = Tarea(descripcion)
        self.tareas.append(tarea)
        print(f"Tarea agregada: {descripcion}")

    def completar_tarea(self, indice):
        if 0 <= indice < len(self.tareas):
            self.tareas[indice].marcar_completada()
            print(f"Tarea completada: {self.tareas[indice].descripcion}")
        else:
            print("Índice inválido")

    def mostrar_tareas(self):
        if len(self.tareas) == 0:
            print("No hay tareas")
            return

        print("\n--- Lista de Tareas ---")
        for i, tarea in enumerate(self.tareas):
            print(f"{i}. {tarea}")

In [ ]:
# Usar el sistema
lista = ListaTareas()
lista.agregar_tarea("Estudiar Python")
lista.agregar_tarea("Hacer ejercicio")
lista.agregar_tarea("Leer un libro")
lista.mostrar_tareas()

lista.completar_tarea(0)
lista.mostrar_tareas()

Tarea agregada: Estudiar Python
Tarea agregada: Hacer ejercicio
Tarea agregada: Leer un libro

--- Lista de Tareas ---
0. [○] Estudiar Python
1. [○] Hacer ejercicio
2. [○] Leer un libro
Tarea completada: Estudiar Python

--- Lista de Tareas ---
0. [✓] Estudiar Python
1. [○] Hacer ejercicio
2. [○] Leer un libro

**Modificando y Eliminando Atributos**

In [ ]:
class Persona:
    def __init__(self, nombre, edad):
        self.nombre = nombre
        self.edad = edad

persona = Persona("Ana", 25)

In [ ]:
# Modificar atributo
persona.edad = 26
print(persona.edad)  # 26

26

In [ ]:
# Agregar nuevo atributo
persona.ciudad = "Lima"
print(persona.ciudad)  # Lima

Lima

In [ ]:
# Eliminar atributo
del persona.ciudad

In [ ]:
# Eliminar objeto completo
del persona